### ISSUE TITLE
TypeError: size must be positive

### ISSUE THREAD

**Issue by BridgeAR** [nearform/node-clinic#16] opened 2018-04-12 19:18 UTC
```
analysing data
/home/ruben/.nvm/versions/node/v9.11.1/lib/node_modules/clinic/node_modules/distributions/distributions/binomial.js:17
    throw TypeError('size must be positive');
    ^

TypeError: size must be positive
    at new BinomialDistribution (/home/ruben/.nvm/versions/node/v9.11.1/lib/node_modules/clinic/node_modules/distributions/distributions/binomial.js:17:11)
    at analyseHandles (/home/ruben/.nvm/versions/node/v9.11.1/lib/node_modules/clinic/node_modules/@nearform/clinic-doctor/analysis/analyse-handles.js:63:20)
    at /home/ruben/.nvm/versions/node/v9.11.1/lib/node_modules/clinic/node_modules/@nearform/clinic-doctor/analysis/index.js:60:18
    at /home/ruben/.nvm/versions/node/v9.11.1/lib/node_modules/clinic/node_modules/async/dist/async.js:3874:9
    at /home/ruben/.nvm/versions/node/v9.11.1/lib/node_modules/clinic/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/home/ruben/.nvm/versions/node/v9.11.1/lib/node_modules/clinic/node_modules/async/dist/async.js:980:24)
    at /home/ruben/.nvm/versions/node/v9.11.1/lib/node_modules/clinic/node_modules/async/dist/async.js:958:16
    at /home/ruben/.nvm/versions/node/v9.11.1/lib/node_modules/clinic/node_modules/async/dist/async.js:3871:13
    at Endpoint.finish (/home/ruben/.nvm/versions/node/v9.11.1/lib/node_modules/clinic/node_modules/endpoint/endpoint.js:36:5)
    at Object.onceWrapper (events.js:272:13)
```

```js
'use strict';

let i = 0;

const obj = {};

while (i++ < 500) {
  obj[i] = {};
}

const circular = {};

for (const k of Object.keys(obj)) {
  circular[k] = obj[k];
  obj[k]._circular = circular;
  obj[k]._obj = obj;
}

console.log(obj);

setTimeout(() => {}, 100);
```

**Comment by mafintosh** [comment] 2018-04-13 13:53
Should be a better error in latest doctor now

**Comment by mafintosh** [comment] 2018-04-13 13:55
(I also cannot reproduce @BridgeAR original error, even with master)

**Comment by mcollina** [comment] 2018-07-04 08:47
Closing as we cannot reproduce.

**Closed by mcollina** 2018-07-04 08:47 UTC
