### ISSUE TITLE
Flame:  v8 log conversion failed

### ISSUE THREAD

**Issue by ttessarolo** [nearform/node-clinic#55] opened 2018-09-18 15:59 UTC
## Expected Behavior
Generate and open Flamegraph

## Current Behavior
Error: v8 log conversion failed

## Steps to Reproduce (for bugs)
0. I'm using a basic node.js app just for test:

var express = require("express");
var app = express();

app.get("/", function(req, res) {
  res.send("Hello World");
});

app.listen(3097);

1. using Node.js v.10.10.0 (with both clinic doctor + autocannon installed -g)
2. clinic flame --on-port='autocannon -c 100 localhost:$PORT' -- node index.js
3. when autocannon finish it produce the following error: Error: v8 log conversion failed
4. Switching to Node.js v8.12.0 -- nvm use v8.12.0 -- (with both clinic doctor + autocannon installed -g) and running exactly the same command it generates correctly the flamegraph

## Environment
@nearform/doctor@3.3.0
autocannon@2.4.1

* Node version: Node.js v.10.10.0

* OSX 10.13.6 (17G2307)

**Comment by mcollina** [comment] 2018-09-18 16:05
Thanks for reporting, this is actually a regression in Node.js 10 which will be fixed in 10.11, coming out later today.

**Comment by BridgeAR** [comment] 2018-09-18 16:07
Duplicate of https://github.com/davidmarkclements/0x/issues/163

**Comment by ttessarolo** [comment] 2018-09-18 16:17
great thanks

**Comment by DylanC** [comment] 2020-02-14 11:26
@mcollina - Should this and the related 0x issue be closed since the fix is released into Node?

**Comment by jasnell** [comment] 2020-02-14 14:54
While I'm not @mcollina (who could be! ;-) ) I definitely think we can close this one

**Closed by jasnell** 2020-02-14 14:54 UTC
