### ISSUE TITLE
Uncaught SyntaxError: Missing initializer in const declaration

### ISSUE THREAD

**Issue by bodinsamuel** [nearform/node-clinic#250] opened 2020-06-05 12:06 UTC
## Expected Behavior
Working

## Current Behavior
After clinic as run the html report is broken with error.
`14030.clinic-doctor.html:7476 Uncaught SyntaxError: Missing initializer in const declaration`

This error happen with doctor and with bubbleproof.

<img width="1432" alt="Screenshot 2020-06-05 14 06 14" src="https://user-images.githubusercontent.com/1637651/83874438-bcbf9980-a735-11ea-9ab8-4be08e7e4cf6.png">

## Steps to Reproduce (for bugs)

1. clinic doctor -- node yourscript
2. ctrl + c
3. open the report in chrome
4. error in console

N.B: also broken on your website :/

## Sample upload
This has nothing to do with report, it's working once all js errors are fixed

## Environment

* Clinic.js version: 6.0.0

* Node.js version:12.16.1

* Browser name and version: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

* Operating system and version: osx catalina 10.15.5

**Comment by javaHashbrown** [comment] 2020-06-05 13:13
@bodinsamuel Came across the same issue. 

I copied all scripts inside the last script tag in the html, found `const EventEmitter,`， and replaced them all with `const EventEmitter=require('events'),`. After that everything was fine.

I guess this is a babel issue but I cannot pinpoint where the problem is. Anyways, hope this helps.

**Comment by jasnell** [comment] 2020-06-05 13:40
Will investigate, thank you! :-)

**Comment by bodinsamuel** [comment] 2020-06-05 14:15
yep I can confirm, this is the same issue happening, I saw one with `let HtmlContent;require('./content-html.js);`.
The actual code seems fine so I wonder what happened in the compilation

**Comment by NomadXD** [comment] 2020-06-07 15:20
I got the same issue but no solution. Any updates ?

**Comment by jasnell** [comment] 2020-06-07 21:10
Should have a fix in by Monday end of day.

**Comment by TomVance** [comment] 2020-06-23 14:32
Hey 👋 

Is this issue still being looked into? Happy to help where I can but not to familiar with the setup here. I can work around the doctor report with the suggestions above however, unable to resolve the same issues with my bubbleprof out put.

Any suggestions would be much appreciated :)

Tom

**Comment by jasnell** [comment] 2020-06-23 15:53
What version are you using? I believe it should have been fixed in the latest version.

**Comment by admataz** [comment] 2020-06-30 12:11
hey @TomVance  - can you confirm which versions are installed on your local environment? - specifically the `@nearform/clinic-common` dependency. 

If you run the command `npm list @nearform/clinic-common -g` you should get something like the output below. 

![image](https://user-images.githubusercontent.com/395101/86124439-0bf9af80-bad3-11ea-9a60-89abdf635a03.png)

If you somehow have a previous version installed, can you try `npm install clinic -g` again to update to the latest?

**Comment by TomVance** [comment] 2020-06-30 12:47
Apologies for my delay in getting back to you:

```
/Users/thomasvance/.nodenv/versions/14.3.0/lib
└─┬ clinic@6.0.2
  ├─┬ @nearform/bubbleprof@4.0.2
  │ └── @nearform/clinic-common@3.2.1
  ├─┬ @nearform/doctor@5.0.2
  │ └── @nearform/clinic-common@3.2.1  deduped
  └─┬ @nearform/flame@6.0.1
    └── @nearform/clinic-common@3.2.1  deduped
```

**Comment by admataz** [comment] 2020-07-01 09:56
Thank you @TomVance  - that looks as it should be

Can you confirm the error you are getting in the console after running a fresh `clinic bubbleprof -- node yourscript`?

**Comment by admataz** [comment] 2020-07-14 09:59
According to all reports and testing this is now working as expected. 🎉  The minor version bump fixed the dependencies.

**Closed by admataz** 2020-07-14 09:59 UTC
