### ISSUE TITLE
Any help with a trace rename error? Thoughts?

### ISSUE THREAD

**Issue by cdbattags** [nearform/node-clinic#6] opened 2018-02-01 16:45 UTC
line 209 in bin.js

Error:

```
Error: ENOENT: no such file or directory, rename 'node_trace.1.log' -> '46525.clinic-doctor/46525.clinic-doctor-traceevent'
    at Error (native)
```

**Comment by dhyasama** [comment] 2018-02-01 17:52
+1 I get the same error

**Comment by AndreasMadsen** [comment] 2018-02-01 22:16
What node version are you using? Until node 8.10.0 is release, we recommend you use 9.4.0.

**Comment by pinturic** [comment] 2018-02-02 09:04
Same error with node v6.5.0

**Comment by dhyasama** [comment] 2018-02-02 14:29
I'm back on 6.11. I'll give 9.4 a try. Thanks!

**Comment by jiripospisil** [comment] 2018-02-02 17:16
I'm getting the same thing on Node 9.4.0 (+ macOS 10.13.3, clinic v0.6.2)

```
/Users/jiripospisil/.nah/versions/release--v9.4.0/lib/node_modules/clinic/bin.js:209
      if (err) throw err
               ^

Error: ENOENT: no such file or directory, rename 'node_trace.1.log' -> '40419.clinic-doctor/40419.clinic-doctor-traceevent'
```

**Comment by jiripospisil** [comment] 2018-02-02 17:27
Ah, it's because my app catches `SIGINT` (which I guess should trigger the dump of the trace) and does some clean up. If I remove the signal catching, it works fine.

**Comment by AndreasMadsen** [comment] 2018-02-03 19:03
@jiripospisil That sounds odd. We collect the data continually and flush the final data on process exit. The flushing part is a bit complicated when the process doesn't exit nicely, and works best when the process exits naturally. Thus I would actually recommend you to add a SIGINT handler that closes everything nicely. See for example our `slow-io` example: https://github.com/nearform/node-clinic-examples/blob/master/slow-io/index.js#L29

PS: We have already made a few improvement to node.js itself, such it works better when there is no SIGINT handler. However, it is an ongoing effort.

**Comment by jiripospisil** [comment] 2018-02-03 19:33
@AndreasMadsen  Hmm, so the difference seems to be that I use `process.once` instead of `process.on`. If works fine if leave the example as is.

```
/tmp/tp-20180203201937/node-clinic-examples/slow-io ∴ master gd
diff --git a/slow-io/index.js b/slow-io/index.js
index 079d5dc..26ba90e 100644
--- a/slow-io/index.js
+++ b/slow-io/index.js
@@ -26,7 +26,7 @@ server.get('/', function (req, res, next) {

 server.listen(3000)

-process.on('SIGINT', function () {
+process.once('SIGINT', function () {
   console.error('Caught SIGINT, shutting down.')
   server.close()
 })
/tmp/tp-20180203201937/node-clinic-examples/slow-io ∴ master clinic doctor -- node index.js
Warning: Trace event is an experimental feature and could change at any time.
^C/Users/jiripospisil/.nah/versions/release--v9.4.0/lib/node_modules/clinic/bin.js:209
      if (err) throw err
               ^

Error: ENOENT: no such file or directory, rename 'node_trace.1.log' -> '43741.clinic-doctor/43741.clinic-doctor-traceevent'
```

**Comment by AndreasMadsen** [comment] 2018-02-03 19:56
@jiripospisil Thanks, I can reproduce the issue – it is quite odd. I will have a look on Monday.

**Comment by cdbattags** [comment] 2018-02-07 14:56
Any updates on this? Anything I can do to help?

**Comment by AndreasMadsen** [comment] 2018-02-07 15:21
I traced it down to this bug https://github.com/nodejs/node/issues/18600 – We have a workaround for another nodecore bug, that as a side-effect will also workaround this nodecore bug: https://github.com/nearform/node-clinic-doctor/pull/100

I will push for it getting landed soon :)

**Comment by AndreasMadsen** [comment] 2018-02-07 15:27
We published a new version of `@nearform/clinic-doctor`, if you update `clinic` it should work now :)

**Comment by mafintosh** [comment] 2018-03-07 10:14
I think this has been fixed. If not please reopen :)

**Closed by mafintosh** 2018-03-07 10:14 UTC
Labels: confirmed bug, norecore issue

**Comment by nithinputhenveettil** [comment] 2018-04-06 04:08
Getting the same error today! Any help?

**Comment by nithinputhenveettil** [comment] 2018-04-06 05:33
Getting the same error on Node v6 today! Any help?

**Comment by mcollina** [comment] 2018-04-06 05:41
Node 6 is not supported. Use Node 8.10z

**Comment by Ahimta** [comment] 2019-01-29 06:53
Getting the same error on Node 10.15.0:sweat_smile:.

I'm using it with Mocha so the NPM script is something like `clinic doctor -- npm run test:unit`. And the `test:unit` is something like `NODE_ENV=test mocha --exit --reporter nyan src/*.spec.js` and I tried to remove the `--exit` flag in case it has some weird process signal handling behavior but it still didn't work:sweat_smile:.

**Comment by Ahimta** [comment] 2019-01-29 07:55
The error doesn't happen anymore when I switched from using `yarn run` to `npm run`:sweat_smile:.

**Comment by ShivaPrabhakar** [comment] 2020-07-22 06:59
How can I change the directory where the node_trace.*.log should go
